Get server running and clean up.

diff --git a/lighttpd-serve b/lighttpd-serve
--- a/lighttpd-serve
+++ b/lighttpd-serve
@@ -1,19 +1,25 @@
 #!/bin/sh
 
+if [ ! -d "build" ]; then
+  echo "Can't find build directory, did you 'npm install' and 'npm run build'?" >/dev/stderr
+  exit 255
+fi
+
+(cd build && ln -fs . chromattis)
+
 DEFAULT_PORT=60999
 EXE_DIR=$(cd "$(dirname "$0")" && pwd)
-SITE_BASE=$(cd "$1" && pwd)
-[ -z "$SITE_BASE" ] && SITE_BASE=$(cd "$(dirname "$0")" && pwd)
+SITE_BASE="$EXE_DIR"
 
 CONFIG="$SITE_BASE/.lighttpd.conf"
 TEMPLATE="$EXE_DIR/lighttpd.conf.template"
 
-PORT=$2
+PORT=$1
 [ -z "$PORT" ] && PORT=$(cat "$SITE_BASE/.lighttpd.port" 2>/dev/null)
 [ -z "$PORT" ] && PORT=$(cat "$SITE_BASE/.port" 2>/dev/null)
 [ -z "$PORT" ] && PORT=$DEFAULT_PORT
 
-echo "Serving on port $PORT in $SITE_BASE."
+echo "Serving on port $PORT in $SITE_BASE"
 #[ "$PORT" = "$DEFAULT_PORT" ] && echo "WARNING: Using the default port, please configure a different one!"
 sed "s|{{SITE_BASE}}|$SITE_BASE|;s|{{PORT}}|$PORT|" "$TEMPLATE" > "$CONFIG"
 /usr/sbin/lighttpd -D -f "$CONFIG"
